theme: jekyll-theme-cayman
title: Machine Reading Comprehension
description: This project is a Machine Reading Comprehension (MRC) framework in TensorFlow. It also contains several classic models (e.g. QANet, BiDAF, etc.) re-implementation and their benchmarks on SQuAD dataset.
